name: 'river_health_dbt'
version: '1.0.0'
config-version: 2

profile: 'river_health_dbt'

model-paths: ['models']
macro-paths: ['macros']
test-paths: ['tests']
analysis-paths: ['analysis']
seed-paths: ['seeds']

target-path: 'target'
clean-targets:
  - 'target'
  - 'dbt_packages'

models:
  river_health_dbt:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts
